"use client"
import { useEffect,useState } from "react"
import { Button } from "@/components/ui/button"
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input";import { Label } from "@/components/ui/label";import { Textarea } from "@/components/ui/textarea"
import type { VolunteerCampaign } from "@/lib/volunteers"
const PRIVACY="Declaro que li e estou ciente de que a AFAPAN utilizará os dados informados neste formulário para organizar ações de voluntariado, manter contato comigo e administrar o cadastro de voluntários, conforme o aviso de privacidade apresentado."
const PARTICIPATION="Confirmo que desejo continuar participando como voluntário(a) da AFAPAN e autorizo o contato pelos canais informados, inclusive pelo WhatsApp, no grupo de voluntários ativos."
export function VolunteerCampaignDialog({open,onOpenChange,campaign,onSave,saving=false}:{open:boolean;onOpenChange:(v:boolean)=>void;campaign:VolunteerCampaign|null;onSave:(v:any)=>Promise<boolean>;saving?:boolean}){const [name,setName]=useState("");const [deadline,setDeadline]=useState("");const [active,setActive]=useState(true);const [privacy,setPrivacy]=useState(PRIVACY);const [participation,setParticipation]=useState(PARTICIPATION);useEffect(()=>{if(!open)return;setName(campaign?.name||"Confirmação de voluntários AFAPAN");setDeadline(campaign?.deadline?new Date(campaign.deadline).toISOString().slice(0,16):new Date(Date.now()+7*86400000).toISOString().slice(0,16));setActive(campaign?.active??true);setPrivacy(campaign?.privacyText||PRIVACY);setParticipation(campaign?.participationText||PARTICIPATION)},[open,campaign]);const save=async()=>{if(!name.trim()||!deadline)return;if(await onSave({id:campaign?.id,expectedUpdatedAt:campaign?.updatedAt,name,deadline:new Date(deadline).toISOString(),active,privacyText:privacy,privacyVersion:campaign?.privacyVersion||"1",participationText:participation,participationVersion:campaign?.participationVersion||"1"}))onOpenChange(false)};return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Campanha de confirmação</DialogTitle><DialogDescription>Configure o prazo e os textos do link público.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label>Nome *</Label><Input value={name} onChange={e=>setName(e.target.value)} /></div><div><Label>Prazo *</Label><Input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)} /></div><label className="flex gap-2"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)} />Campanha ativa</label><div><Label>Ciência sobre uso dos dados</Label><Textarea rows={4} value={privacy} onChange={e=>setPrivacy(e.target.value)} /></div><div><Label>Interesse e autorização de contato</Label><Textarea rows={4} value={participation} onChange={e=>setParticipation(e.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?"Salvando...":"Salvar campanha"}</Button></DialogFooter></DialogContent></Dialog>}
