"use client"

import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { VOLUNTEER_ACTIVITIES, VOLUNTEER_DAYS, VOLUNTEER_FREQUENCIES, VOLUNTEER_SHIFTS, isMinor, validateVolunteerInput, type Volunteer, type VolunteerActivity, type VolunteerDay, type VolunteerFrequency, type VolunteerInput, type VolunteerShift, type VolunteerStatus } from "@/lib/volunteers"

interface Props { open: boolean; onOpenChange: (open: boolean) => void; volunteer?: Volunteer | null; onSave: (input: VolunteerInput & { status?: VolunteerStatus }) => Promise<boolean>; saving?: boolean }
const empty: VolunteerInput = { firstName:"",lastName:"",birthDate:"",phone:"",email:"",street:"",number:"",complement:"",neighborhood:"",city:"Farroupilha",state:"RS",profession:"",skills:"",activityStartMonth:null,activityStartYear:null,availableDays:[],availableShifts:[],frequency:"eventual",availabilityNotes:"",activities:[],otherActivityDescription:"",guardianName:"",guardianPhone:"",guardianAuthorized:false,privacyAccepted:true,participationAccepted:true }

export function VolunteerFormDialog({ open,onOpenChange,volunteer,onSave,saving=false }: Props) {
  const [value,setValue]=useState<VolunteerInput>(empty); const [status,setStatus]=useState<VolunteerStatus>("ativo"); const [start,setStart]=useState(""); const [error,setError]=useState<string|null>(null)
  useEffect(()=>{ if(!open)return; setValue(volunteer ? { ...volunteer } : empty); setStatus(volunteer?.status || "ativo"); setStart(volunteer?.activityStartMonth&&volunteer.activityStartYear ? `${volunteer.activityStartYear}-${String(volunteer.activityStartMonth).padStart(2,"0")}`:""); setError(null) },[open,volunteer])
  const update=<K extends keyof VolunteerInput>(key:K,next:VolunteerInput[K])=>setValue(current=>({...current,[key]:next}))
  const toggle=(field:"availableDays"|"availableShifts"|"activities",item:string,checked:boolean)=>update(field as keyof VolunteerInput,(checked?[...(value[field] as string[]),item]:(value[field] as string[]).filter(v=>v!==item)) as never)
  const save=async()=>{const errors=validateVolunteerInput(value);if(errors.length){setError(errors[0].message);return}if(await onSave({...value,status}))onOpenChange(false)}
  const month=(next:string)=>{setStart(next);const [year,month]=next.split("-").map(Number);update("activityStartMonth",next?month:null);update("activityStartYear",next?year:null)}
  const check=(label:string,checked:boolean,onChange:(v:boolean)=>void)=><label className="flex gap-2 text-sm"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} />{label}</label>
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>{volunteer?"Editar voluntário":"Cadastrar voluntário"}</DialogTitle><DialogDescription>Cadastro assistido pela equipe da AFAPAN.</DialogDescription></DialogHeader><div className="space-y-5 py-2">
    <div className="grid gap-4 sm:grid-cols-2"><div><Label>Nome *</Label><Input value={value.firstName} onChange={e=>update("firstName",e.target.value)} /></div><div><Label>Sobrenome *</Label><Input value={value.lastName} onChange={e=>update("lastName",e.target.value)} /></div><div><Label>Data de nascimento *</Label><Input type="date" value={value.birthDate} onChange={e=>update("birthDate",e.target.value)} /></div><div><Label>Telefone com WhatsApp *</Label><Input value={value.phone} onChange={e=>update("phone",e.target.value)} /></div><div><Label>E-mail</Label><Input type="email" value={value.email} onChange={e=>update("email",e.target.value)} /></div><div><Label>Início na AFAPAN</Label><Input type="month" value={start} max={new Date().toISOString().slice(0,7)} onChange={e=>month(e.target.value)} /></div></div>
    <div className="grid gap-4 sm:grid-cols-2"><div><Label>Bairro *</Label><Input value={value.neighborhood} onChange={e=>update("neighborhood",e.target.value)} /></div><div><Label>Cidade *</Label><Input value={value.city} onChange={e=>update("city",e.target.value)} /></div><div><Label>Rua</Label><Input value={value.street} onChange={e=>update("street",e.target.value)} /></div><div><Label>Número</Label><Input value={value.number} onChange={e=>update("number",e.target.value)} /></div><div><Label>Complemento</Label><Input value={value.complement} onChange={e=>update("complement",e.target.value)} /></div><div><Label>Estado</Label><Input value={value.state} onChange={e=>update("state",e.target.value)} /></div></div>
    <div className="grid gap-4 sm:grid-cols-2"><div><Label>Profissão</Label><Input value={value.profession} onChange={e=>update("profession",e.target.value)} /></div><div><Label>Habilidades</Label><Textarea value={value.skills} onChange={e=>update("skills",e.target.value)} /></div></div>
    <fieldset className="space-y-2"><legend className="font-medium">Atividades *</legend><div className="grid gap-2 sm:grid-cols-2">{VOLUNTEER_ACTIVITIES.map(item=>check(item.label,value.activities.includes(item.value),v=>toggle("activities",item.value,v)))}</div></fieldset>{value.activities.includes("outras")&&<div><Label>Descrição das outras atividades *</Label><Textarea value={value.otherActivityDescription} onChange={e=>update("otherActivityDescription",e.target.value)} /></div>}
    <fieldset><legend className="mb-2 font-medium">Dias *</legend><div className="grid gap-2 sm:grid-cols-4">{VOLUNTEER_DAYS.map(item=>check(item.label,value.availableDays.includes(item.value),v=>toggle("availableDays",item.value,v)))}</div></fieldset><fieldset><legend className="mb-2 font-medium">Turnos *</legend><div className="flex flex-wrap gap-5">{VOLUNTEER_SHIFTS.map(item=>check(item.label,value.availableShifts.includes(item.value),v=>toggle("availableShifts",item.value,v)))}</div></fieldset>
    <div className="grid gap-4 sm:grid-cols-2"><div><Label>Frequência *</Label><Select value={value.frequency} onValueChange={(v:VolunteerFrequency)=>update("frequency",v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{VOLUNTEER_FREQUENCIES.map(item=><SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div><div><Label>Situação</Label><Select value={status} onValueChange={(v:VolunteerStatus)=>setStatus(v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="aguardando_validacao">Aguardando validação</SelectItem><SelectItem value="ativo">Ativo</SelectItem><SelectItem value="sem_confirmacao">Sem confirmação</SelectItem><SelectItem value="inativo">Inativo</SelectItem></SelectContent></Select></div></div><div><Label>Observações de disponibilidade</Label><Textarea value={value.availabilityNotes} onChange={e=>update("availabilityNotes",e.target.value)} /></div>
    {value.birthDate&&isMinor(value.birthDate)&&<div className="space-y-3 rounded-lg border border-amber-300 p-4"><p className="font-medium">Responsável pelo menor</p><div className="grid gap-4 sm:grid-cols-2"><div><Label>Nome *</Label><Input value={value.guardianName} onChange={e=>update("guardianName",e.target.value)} /></div><div><Label>Telefone *</Label><Input value={value.guardianPhone} onChange={e=>update("guardianPhone",e.target.value)} /></div></div>{check("Autorização do responsável confirmada",Boolean(value.guardianAuthorized),v=>update("guardianAuthorized",v))}</div>}
    {error&&<p className="text-sm text-destructive">{error}</p>}
  </div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)} disabled={saving}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?"Salvando...":"Salvar"}</Button></DialogFooter></DialogContent></Dialog>
}
